###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - <basedir>/altenv/var/log/collector.log

  document_type: collector
  fields.client: <orgid>
  fields.orgid: 2
  fields.sysid: 15
  fields.token: "571145dfa339dc049c7467475cf82b1b115bca00"
  fields_under_root: true
  close_inactive: 2h
  tail_files: true
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} '
  multiline.negate: true
  multiline.match: after

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/messages

  document_type: system
  fields.orgid: <orgid>
  fields.sysid: <sysid>
  fields.token: <token>
  fields_under_root: true
  close_inactive: 2h
  tail_files: true
  multiline.pattern: '^[a-zA-Z]{3}[ ]{1,2}[0-9]{1,2} [0-9]{2}:[0-9]{2}:[0-9]{2} '
  multiline.negate: true
  multiline.match: after


#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Kafka output ------------------------------
output.kafka:
  # Array of hosts to connect to.
  hosts: [<log-server-host-port>]
  ssl.enabled: true
  version: "0.10"
  topic: 'filebeat.%{[orgid]}.%{[sysid]}'
  partition.round_robin:
    reachable_only: true
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000


#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]

logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: <basedir>/altenv/var/log
  name: filebeat.log
  keepfiles: 4
